"""
Report Generator - Creates PDF and HTML reports
For sharing fact-check results
"""

import os
from datetime import datetime
from typing import List, Dict, Any
from fpdf import FPDF
import base64


class ReportGenerator:
    """Generate shareable fact-check reports in PDF and HTML format."""
    
    def __init__(self):
        self.colors = {
            "TRUE": (212, 237, 218),
            "FALSE": (248, 215, 218),
            "MIXED": (255, 243, 205),
            "UNVERIFIED": (226, 227, 229),
            "MOSTLY_TRUE": (212, 237, 218),
            "MOSTLY_FALSE": (248, 215, 218)
        }
    
    def generate_pdf(self, result, transcript: str) -> bytes:
        """Generate PDF report"""
        pdf = FPDF()
        pdf.add_page()
        
        # Title
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, "Health Claim Fact-Check Report", ln=True, align="C")
        
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 5, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
        pdf.ln(5)
        
        # Video Info
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "Video Information", ln=True)
        pdf.set_font("Arial", "", 10)
        pdf.multi_cell(0, 5, f"URL: {result.url}")
        pdf.cell(0, 5, f"Language: {result.language.title()}", ln=True)
        pdf.ln(3)
        
        # Overall Rating
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "Overall Rating", ln=True)
        pdf.set_font("Arial", "", 10)
        
        verdict_color = self.colors.get(result.overall_rating, (230, 230, 230))
        pdf.set_fill_color(*verdict_color)
        pdf.cell(60, 8, f"Rating: {result.overall_rating}", fill=True)
        pdf.cell(60, 8, f"Confidence: {result.overall_confidence:.0%}", ln=True)
        pdf.cell(60, 8, f"Claims Found: {result.claims_found}", ln=True)
        pdf.ln(3)
        
        # Summary
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "Summary", ln=True)
        pdf.set_font("Arial", "", 10)
        pdf.multi_cell(0, 5, result.summary)
        pdf.ln(3)
        
        # Claims Analysis
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "Detailed Claim Analysis", ln=True)
        pdf.ln(2)
        
        for i, verdict in enumerate(result.verdicts, 1):
            pdf.set_font("Arial", "B", 11)
            pdf.cell(0, 7, f"Claim #{i}", ln=True)
            
            pdf.set_font("Arial", "", 10)
            pdf.multi_cell(0, 5, f"Original: {verdict.claim}")
            
            if verdict.claim != verdict.claim_english:
                pdf.multi_cell(0, 5, f"English: {verdict.claim_english}")
            
            verdict_color = self.colors.get(verdict.verdict, (230, 230, 230))
            pdf.set_fill_color(*verdict_color)
            pdf.cell(50, 6, f"Verdict: {verdict.verdict}", fill=True)
            pdf.cell(50, 6, f"Confidence: {verdict.confidence:.0%}", ln=True)
            pdf.cell(50, 6, f"Category: {verdict.category}", ln=True)
            
            pdf.set_font("Arial", "I", 9)
            pdf.multi_cell(0, 4, f"Explanation: {verdict.explanation}")
            
            if verdict.sources:
                pdf.set_font("Arial", "", 9)
                pdf.cell(0, 5, f"Sources ({len(verdict.sources)}):", ln=True)
                for j, source in enumerate(verdict.sources[:5], 1):
                    pdf.multi_cell(0, 4, f"  {j}. {source}")
            
            pdf.ln(3)
        
        # Disclaimer
        pdf.ln(5)
        pdf.set_font("Arial", "I", 9)
        pdf.set_text_color(128, 128, 128)
        pdf.multi_cell(0, 4, 
            "DISCLAIMER: This report is generated by automated AI analysis and is for informational purposes only. "
            "It should not be used as a substitute for professional medical advice, diagnosis, or treatment. "
            "Always consult qualified healthcare professionals for medical decisions."
        )
        
        # Return as bytes
        return pdf.output(dest='S').encode('latin-1')
    
    def generate_html(self, result, transcript: str) -> str:
        """Generate HTML report"""
        
        # HTML template
        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Health Claim Fact-Check Report</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            text-align: center;
            margin-bottom: 30px;
        }}
        .header h1 {{
            margin: 0;
            font-size: 28px;
        }}
        .header p {{
            margin: 10px 0 0 0;
            opacity: 0.9;
        }}
        .section {{
            background: white;
            padding: 25px;
            margin-bottom: 20px;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .section h2 {{
            margin-top: 0;
            color: #333;
            border-bottom: 2px solid #667eea;
            padding-bottom: 10px;
        }}
        .metrics {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }}
        .metric {{
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            text-align: center;
        }}
        .metric-label {{
            font-size: 12px;
            color: #666;
            text-transform: uppercase;
            margin-bottom: 5px;
        }}
        .metric-value {{
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }}
        .claim-card {{
            background: #f8f9fa;
            border-left: 4px solid #007bff;
            padding: 20px;
            margin: 15px 0;
            border-radius: 5px;
        }}
        .claim-card h3 {{
            margin-top: 0;
            color: #333;
        }}
        .verdict-badge {{
            display: inline-block;
            padding: 5px 15px;
            border-radius: 20px;
            font-weight: bold;
            font-size: 14px;
            margin: 10px 5px 10px 0;
        }}
        .verdict-TRUE, .verdict-MOSTLY_TRUE {{
            background-color: #d4edda;
            color: #155724;
        }}
        .verdict-FALSE, .verdict-MOSTLY_FALSE {{
            background-color: #f8d7da;
            color: #721c24;
        }}
        .verdict-MIXED {{
            background-color: #fff3cd;
            color: #856404;
        }}
        .verdict-UNVERIFIED {{
            background-color: #e2e3e5;
            color: #383d41;
        }}
        .sources {{
            margin-top: 15px;
            padding: 15px;
            background: white;
            border-radius: 5px;
        }}
        .sources h4 {{
            margin-top: 0;
            font-size: 14px;
            color: #666;
        }}
        .sources ul {{
            margin: 5px 0;
            padding-left: 20px;
        }}
        .sources li {{
            margin: 5px 0;
            font-size: 13px;
        }}
        .sources a {{
            color: #007bff;
            text-decoration: none;
        }}
        .sources a:hover {{
            text-decoration: underline;
        }}
        .disclaimer {{
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin-top: 30px;
            border-radius: 5px;
            font-size: 13px;
            color: #856404;
        }}
        .category-tag {{
            display: inline-block;
            background: #e7f3ff;
            color: #0056b3;
            padding: 3px 10px;
            border-radius: 12px;
            font-size: 12px;
            margin-left: 10px;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🏥 Health Claim Fact-Check Report</h1>
        <p>Generated: {datetime.now().strftime('%B %d, %Y at %H:%M:%S')}</p>
    </div>
    
    <div class="section">
        <h2>📹 Video Information</h2>
        <p><strong>URL:</strong> <a href="{result.url}" target="_blank">{result.url}</a></p>
        <p><strong>Language:</strong> {result.language.title()}</p>
    </div>
    
    <div class="section">
        <h2>📊 Overall Assessment</h2>
        <div class="metrics">
            <div class="metric">
                <div class="metric-label">Rating</div>
                <div class="metric-value">{result.overall_rating}</div>
            </div>
            <div class="metric">
                <div class="metric-label">Confidence</div>
                <div class="metric-value">{result.overall_confidence:.0%}</div>
            </div>
            <div class="metric">
                <div class="metric-label">Claims Found</div>
                <div class="metric-value">{result.claims_found}</div>
            </div>
        </div>
        <p><strong>Summary:</strong> {result.summary}</p>
    </div>
    
    <div class="section">
        <h2>🔍 Detailed Claim Analysis</h2>
"""
        
        # Add each claim
        for i, verdict in enumerate(result.verdicts, 1):
            html += f"""
        <div class="claim-card">
            <h3>Claim #{i}</h3>
            <p><strong>Original:</strong> {verdict.claim}</p>
"""
            if verdict.claim != verdict.claim_english:
                html += f"            <p><strong>English:</strong> {verdict.claim_english}</p>\n"
            
            html += f"""
            <div>
                <span class="verdict-badge verdict-{verdict.verdict}">{verdict.verdict}</span>
                <span class="verdict-badge" style="background: #e7f3ff; color: #0056b3;">{verdict.confidence:.0%} Confidence</span>
                <span class="category-tag">{verdict.category}</span>
            </div>
            <p><strong>Analysis:</strong> {verdict.explanation}</p>
"""
            
            if verdict.sources:
                html += f"""
            <div class="sources">
                <h4>📚 Scientific Sources ({len(verdict.sources)})</h4>
                <ul>
"""
                for source in verdict.sources[:10]:
                    html += f'                    <li><a href="{source}" target="_blank">{source}</a></li>\n'
                
                html += """
                </ul>
            </div>
"""
            
            html += "        </div>\n"
        
        # Footer
        html += """
    </div>
    
    <div class="disclaimer">
        <strong>⚠️ DISCLAIMER:</strong> This report is generated by automated AI analysis and is for informational purposes only. 
        It should not be used as a substitute for professional medical advice, diagnosis, or treatment. 
        Always consult qualified healthcare professionals for medical decisions.
    </div>
    
    <div style="text-align: center; margin-top: 30px; color: #666; font-size: 12px;">
        <p>Powered by Health Claim Fact-Checker Pro</p>
        <p>Using Llama 3.3 AI + Medical Databases (PubMed, WHO, FDA, NIH, OpenAlex)</p>
    </div>
</body>
</html>
"""
        
        return html