"""
Smart Transcript Corrector - Uses Llama to fix transcription errors
Works for ANY unknown medical/health terms
Enhanced with better prompting and fallback strategies
"""

import os
import re
from typing import Dict, List, Optional
from groq import Groq


class TranscriptCorrector:
    """
    Uses Llama AI to intelligently correct transcription errors.
    No hardcoded dictionary - works for any term!
    """
    
    CORRECTION_PROMPT = """You are a medical transcription expert. The following transcript was generated by speech-to-text AI from a health/medical video. It may contain errors, especially in medical/scientific terms.

YOUR TASK:
1. Read the transcript carefully
2. Identify any words that seem like transcription errors (especially medical/scientific terms)
3. Correct them based on context
4. Return ONLY the corrected transcript, nothing else

COMMON TRANSCRIPTION ERRORS TO LOOK FOR:
- Chemical names (e.g., "acral mites" → "acrylamide", "acryl amide" → "acrylamide")
- Medical terms (e.g., "die a betes" → "diabetes", "hyper tension" → "hypertension")  
- Scientific terms (e.g., "carsino gen" → "carcinogen", "anti oxidant" → "antioxidant")
- Drug names, vitamin names, disease names
- Units (e.g., "micro gram" → "microgram", "milli liter" → "milliliter")
- Hindi/Urdu medical terms transcribed incorrectly in English

IMPORTANT RULES:
- Keep the original meaning intact
- Only fix obvious transcription errors
- Don't change correct words
- Don't add or remove content
- Preserve the speaker's intent
- If a word seems wrong but you're not sure, leave it as is
- Maintain the same language (don't translate Hindi to English)

ORIGINAL TRANSCRIPT:
{transcript}

CORRECTED TRANSCRIPT (return ONLY the corrected text, no preamble):"""

    # Extended dictionary for common medical term errors
    MEDICAL_CORRECTIONS = {
        # Acrylamide variations
        "acral mites": "acrylamide",
        "acral mite": "acrylamide",
        "acryl mites": "acrylamide",
        "acral might": "acrylamide",
        "acryl amide": "acrylamide",
        "acrylmide": "acrylamide",
        "acrylamid": "acrylamide",
        
        # Carcinogen
        "carcino gen": "carcinogen",
        "karcinogen": "carcinogen",
        "carcinogene": "carcinogen",
        
        # Common diseases
        "die a betes": "diabetes",
        "dia betes": "diabetes",
        "diabetes mellitus": "diabetes mellitus",
        "hyper tension": "hypertension",
        "cardio vascular": "cardiovascular",
        "osteo porosis": "osteoporosis",
        "arthri tis": "arthritis",
        
        # Cholesterol
        "coles terol": "cholesterol",
        "cholestrol": "cholesterol",
        "chole sterol": "cholesterol",
        
        # Vitamins & minerals
        "vitamin d": "vitamin D",
        "vitamin b12": "vitamin B12",
        "vitamin b 12": "vitamin B12",
        "cal cium": "calcium",
        "magne sium": "magnesium",
        "pota ssium": "potassium",
        
        # Common health terms
        "anti oxidant": "antioxidant",
        "anti biotic": "antibiotic",
        "pro biotic": "probiotic",
        "meta bolism": "metabolism",
        "in flammation": "inflammation",
        "anti inflammatory": "anti-inflammatory",
        
        # Units
        "micro gram": "microgram",
        "milli gram": "milligram",
        "kilo calorie": "kilocalorie",
        "milli liter": "milliliter",
        
        # Others
        "ome ga 3": "omega-3",
        "ome ga 6": "omega-6",
        "glu ten": "gluten",
        "lac tose": "lactose",
    }

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("GROQ_API_KEY")
        self.client = None
        
        if self.api_key:
            try:
                self.client = Groq(api_key=self.api_key)
            except Exception as e:
                print(f"[!] Failed to initialize Groq client: {e}")
                self.client = None
    
    def correct(self, transcript: str) -> Dict:
        """
        Correct transcript using Llama AI with fallback to dictionary.
        
        Returns:
            Dict with corrected transcript and metadata
        """
        if not transcript or len(transcript.strip()) < 20:
            return {
                "corrected": transcript,
                "original": transcript,
                "corrections_made": False,
                "method": "skipped_too_short"
            }
        
        # Try AI correction first
        if self.client:
            ai_result = self._ai_correction(transcript)
            if ai_result["corrections_made"]:
                return ai_result
        
        # Fallback to dictionary corrections
        dict_corrected = self._dictionary_corrections(transcript)
        return {
            "corrected": dict_corrected,
            "original": transcript,
            "corrections_made": dict_corrected != transcript,
            "method": "dictionary_fallback"
        }
    
    def _ai_correction(self, transcript: str) -> Dict:
        """Use Llama AI for corrections"""
        try:
            print("[*] Correcting transcript with Llama AI...")
            
            response = self.client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {
                        "role": "system",
                        "content": "You are a medical transcription expert. Fix transcription errors in health/medical content. Return ONLY the corrected text, no preamble, no explanation."
                    },
                    {
                        "role": "user", 
                        "content": self.CORRECTION_PROMPT.format(transcript=transcript[:4000])
                    }
                ],
                temperature=0.1,  # Low temperature for consistent corrections
                max_tokens=2000
            )
            
            corrected = (response.choices[0].message.content or "").strip()
            
            # Clean up response
            corrected = self._clean_response(corrected, transcript)
            
            if corrected != transcript:
                print("[*] ✨ Transcript corrections applied by Llama AI")
                self._show_diff(transcript, corrected)
                
                return {
                    "corrected": corrected,
                    "original": transcript,
                    "corrections_made": True,
                    "method": "llama_ai"
                }
            else:
                print("[*] No corrections needed (AI)")
                return {
                    "corrected": transcript,
                    "original": transcript,
                    "corrections_made": False,
                    "method": "llama_ai_no_changes"
                }
            
        except Exception as e:
            print(f"[!] Llama correction failed: {e}")
            return {
                "corrected": transcript,
                "original": transcript,
                "corrections_made": False,
                "method": "ai_error"
            }
    
    def _dictionary_corrections(self, transcript: str) -> str:
        """Apply dictionary-based corrections"""
        result = transcript
        corrections_applied = []
        
        for wrong, correct in self.MEDICAL_CORRECTIONS.items():
            # Case-insensitive replacement
            pattern = re.compile(re.escape(wrong), re.IGNORECASE)
            if pattern.search(result):
                result = pattern.sub(correct, result)
                corrections_applied.append(f"{wrong} → {correct}")
        
        if corrections_applied:
            print(f"[*] Applied {len(corrections_applied)} dictionary corrections")
            for correction in corrections_applied[:5]:  # Show first 5
                print(f"    - {correction}")
        
        return result
    
    def _clean_response(self, response: str, original: str) -> str:
        """Clean up Llama's response to extract just the transcript"""
        # Remove common preambles
        preambles = [
            "Here is the corrected transcript:",
            "Corrected transcript:",
            "Here's the corrected version:",
            "The corrected transcript is:",
            "CORRECTED TRANSCRIPT:",
            "Corrected version:",
        ]
        
        cleaned = response
        for preamble in preambles:
            if cleaned.lower().startswith(preamble.lower()):
                cleaned = cleaned[len(preamble):].strip()
        
        # Remove quotes if wrapped
        if cleaned.startswith('"') and cleaned.endswith('"'):
            cleaned = cleaned[1:-1]
        if cleaned.startswith("'") and cleaned.endswith("'"):
            cleaned = cleaned[1:-1]
        
        # Remove markdown code blocks
        if cleaned.startswith("```") and cleaned.endswith("```"):
            cleaned = cleaned[3:-3].strip()
            if cleaned.startswith("text\n"):
                cleaned = cleaned[5:]
        
        # Sanity check: if response is too different, return original
        len_ratio = len(cleaned) / len(original) if len(original) > 0 else 0
        if len_ratio < 0.5 or len_ratio > 1.5:
            print(f"[!] AI response length too different ({len_ratio:.2f}x), using original")
            return original
        
        return cleaned
    
    def _show_diff(self, original: str, corrected: str):
        """Show what was corrected"""
        orig_words = set(original.lower().split())
        corr_words = set(corrected.lower().split())
        
        removed = orig_words - corr_words
        added = corr_words - orig_words
        
        if removed or added:
            print("[*] Key corrections:")
            for r in list(removed)[:5]:  # Show max 5
                print(f"    - Removed/Changed: '{r}'")
            for a in list(added)[:5]:
                print(f"    + Added/Fixed: '{a}'")


class SmartCorrector:
    """
    Wrapper class for compatibility with existing code.
    """
    
    @staticmethod
    def correct(transcript: str, api_key: Optional[str] = None) -> str:
        """Static method for simple correction calls"""
        corrector = TranscriptCorrector(api_key=api_key)
        result = corrector.correct(transcript)
        return result["corrected"]
    
    @staticmethod
    def get_corrections_made(original: str, corrected: str) -> List[Dict[str, str]]:
        """Get list of word-level changes"""
        orig_words = original.lower().split()
        corr_words = corrected.lower().split()
        
        corrections = []
        
        # Simple word-level diff
        orig_set = set(orig_words)
        corr_set = set(corr_words)
        
        removed = orig_set - corr_set
        added = corr_set - orig_set
        
        for r in removed:
            for a in added:
                # If words are similar length, probably a correction
                if abs(len(r) - len(a)) < 5:
                    corrections.append({"original": r, "corrected": a})
                    break
        
        return corrections