"""
Smart Transcript Corrector - Uses Llama to fix transcription errors
Works for ANY unknown medical/health terms
"""

import os
import re
from typing import Dict, List, Optional
from groq import Groq


class TranscriptCorrector:
    """
    Uses Llama AI to intelligently correct transcription errors.
    No hardcoded dictionary - works for any term!
    """
    
    CORRECTION_PROMPT = """You are a medical transcription expert. The following transcript was generated by speech-to-text AI from a health/medical video. It may contain errors, especially in medical/scientific terms.

YOUR TASK:
1. Read the transcript carefully
2. Identify any words that seem like transcription errors (especially medical/scientific terms)
3. Correct them based on context
4. Return ONLY the corrected transcript, nothing else

COMMON TRANSCRIPTION ERRORS TO LOOK FOR:
- Chemical names (e.g., "acral mites" → "acrylamide")
- Medical terms (e.g., "die a betes" → "diabetes")  
- Scientific terms (e.g., "carsino gen" → "carcinogen")
- Drug names, vitamin names, disease names
- Units (e.g., "micro gram" → "microgram")

IMPORTANT RULES:
- Keep the original meaning intact
- Only fix obvious transcription errors
- Don't change correct words
- Don't add or remove content
- Preserve the speaker's intent
- If a word seems wrong but you're not sure, leave it as is

ORIGINAL TRANSCRIPT:
{transcript}

CORRECTED TRANSCRIPT:"""

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("GROQ_API_KEY")
        self.client = None
        
        if self.api_key:
            self.client = Groq(api_key=self.api_key)
    
    def correct(self, transcript: str) -> Dict:
        """
        Correct transcript using Llama AI.
        
        Returns:
            Dict with corrected transcript and metadata
        """
        if not transcript or len(transcript.strip()) < 20:
            return {
                "corrected": transcript,
                "original": transcript,
                "corrections_made": False,
                "method": "skipped_too_short"
            }
        
        # If no API key, use basic corrections
        if not self.client:
            basic_corrected = self._basic_corrections(transcript)
            return {
                "corrected": basic_corrected,
                "original": transcript,
                "corrections_made": basic_corrected != transcript,
                "method": "basic_dictionary"
            }
        
        try:
            print("[*] Correcting transcript with Llama AI...")
            
            response = self.client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {
                        "role": "system",
                        "content": "You are a medical transcription expert. Fix any transcription errors in health/medical content. Return ONLY the corrected text."
                    },
                    {
                        "role": "user", 
                        "content": self.CORRECTION_PROMPT.format(transcript=transcript)
                    }
                ],
                temperature=0.1,  # Low temperature for consistent corrections
                max_tokens=2000
            )
            
            corrected = (response.choices[0].message.content or "").strip()
            
            # Clean up response (remove any preamble if Llama added it)
            corrected = self._clean_response(corrected, transcript)
            
            if corrected != transcript:
                print("[*] Transcript corrections applied by Llama")
                self._show_diff(transcript, corrected)
            
            return {
                "corrected": corrected,
                "original": transcript,
                "corrections_made": corrected != transcript,
                "method": "llama_ai"
            }
            
        except Exception as e:
            print(f"[!] Llama correction failed: {e}")
            # Fallback to basic corrections
            basic_corrected = self._basic_corrections(transcript)
            return {
                "corrected": basic_corrected,
                "original": transcript,
                "corrections_made": basic_corrected != transcript,
                "method": "basic_fallback"
            }
    
    def _clean_response(self, response: str, original: str) -> str:
        """Clean up Llama's response to extract just the transcript."""
        # Remove common preambles
        preambles = [
            "Here is the corrected transcript:",
            "Corrected transcript:",
            "Here's the corrected version:",
            "The corrected transcript is:",
            "CORRECTED TRANSCRIPT:",
        ]
        
        cleaned = response
        for preamble in preambles:
            if cleaned.lower().startswith(preamble.lower()):
                cleaned = cleaned[len(preamble):].strip()
        
        # Remove quotes if wrapped
        if cleaned.startswith('"') and cleaned.endswith('"'):
            cleaned = cleaned[1:-1]
        
        # If response is too different (>50% change), return original
        if len(cleaned) < len(original) * 0.5 or len(cleaned) > len(original) * 1.5:
            return original
        
        return cleaned
    
    def _show_diff(self, original: str, corrected: str):
        """Show what was corrected."""
        orig_words = set(original.lower().split())
        corr_words = set(corrected.lower().split())
        
        removed = orig_words - corr_words
        added = corr_words - orig_words
        
        if removed or added:
            print("[*] Key corrections:")
            for r in list(removed)[:5]:  # Show max 5
                print(f"    - Removed/Changed: '{r}'")
            for a in list(added)[:5]:
                print(f"    + Added/Fixed: '{a}'")
    
    def _basic_corrections(self, transcript: str) -> str:
        """Basic dictionary-based corrections as fallback."""
        corrections = {
            # Acrylamide
            "acral mites": "acrylamide",
            "acral mite": "acrylamide",
            "acryl mites": "acrylamide",
            "acral might": "acrylamide",
            "acryl amide": "acrylamide",
            "acrylmide": "acrylamide",
            
            # Carcinogen
            "carcino gen": "carcinogen",
            "karcinogen": "carcinogen",
            
            # Common medical terms
            "die a betes": "diabetes",
            "dia betes": "diabetes",
            "coles terol": "cholesterol",
            "hyper tension": "hypertension",
            "cardio vascular": "cardiovascular",
        }
        
        result = transcript
        for wrong, correct in corrections.items():
            pattern = re.compile(re.escape(wrong), re.IGNORECASE)
            result = pattern.sub(correct, result)
        
        return result


class SmartCorrector:
    """
    Wrapper class for compatibility with existing code.
    """
    
    @staticmethod
    def correct(transcript: str, api_key: Optional[str] = None) -> str:
        """Static method for simple correction calls."""
        corrector = TranscriptCorrector(api_key=api_key)
        result = corrector.correct(transcript)
        return result["corrected"]
    
    @staticmethod
    def get_corrections_made(original: str, corrected: str) -> List[Dict[str, str]]:
        """Get list of word-level changes."""
        orig_words = original.lower().split()
        corr_words = corrected.lower().split()
        
        corrections = []
        
        # Simple word-level diff
        orig_set = set(orig_words)
        corr_set = set(corr_words)
        
        removed = orig_set - corr_set
        added = corr_set - orig_set
        
        for r in removed:
            for a in added:
                # If words are similar length, probably a correction
                if abs(len(r) - len(a)) < 5:
                    corrections.append({"original": r, "corrected": a})
                    break
        
        return corrections